CREATE TABLE [dbo].[Tweets](
	[TweetsID] [INT] IDENTITY(1,1) NOT NULL,
	[Date] [DATETIME] NOT NULL,
	[UserName] [NVARCHAR](20) NOT NULL,
	[Tweet] [NVARCHAR](MAX) NOT NULL,
	[UserLocation] [NVARCHAR](50) NOT NULL,
	[Sentiment] [DECIMAL](5, 4) NOT NULL,
	[__PowerAppsId__] [NVARCHAR](50) NULL,
 CONSTRAINT [PK_Tweets] PRIMARY KEY CLUSTERED 
(
	[TweetsID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];
